# Generated by Django 4.1.4 on 2022-12-26 18:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweat',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
