# Generated by Django 4.1.4 on 2022-12-27 12:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sweat_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
